source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails", "~> 5.0.7"
gem "sqlite3", '~> 1.3.6'
gem "puma"
gem "webpacker"
gem "bootsnap", require: false

group :development, :test do
  gem "cypress-rails", path: "../.."
end
